"""Commands for development inspection and smoke validation."""

import asyncio
from pathlib import Path

import typer

from ...core.models import AgentStage
from ...events import (
    RunEventDraft,
    EventLevel,
    EventPublisher,
)
from ...run_storage import RunRepository, RunStatus
from ...runtime.agent_runtime import generate_run_id
from ..context import get_cli_context
from ..rich_events import RichEventSink, RichRenderer


dev_app = typer.Typer(
    name="dev",
    help="Development helpers that do not call a real Agent, LLM, or solver.",
    no_args_is_help=True,
)


async def _publish_demo_events(
    *,
    repository: RunRepository,
    run_id: str,
    console,
    debug: bool,
    timestamps: bool,
) -> None:
    sink = RichEventSink(
        console,
        RichRenderer(debug=debug, show_timestamps=timestamps or debug),
    )
    publisher = EventPublisher(sink, run_id=run_id)

    await publisher.publish(RunEventDraft(type="run_created", message="Created event-stream demo Run"))
    repository.update_record(run_id, status=RunStatus.RUNNING)
    await publisher.publish(RunEventDraft(type="run_started", message="Started simulated optimization"))
    await publisher.publish(
        RunEventDraft(
            type="user_message",
            stage=AgentStage.INTAKE,
            message="Create a minimum-cost delivery plan for warehouse orders.",
        )
    )
    await publisher.publish(
        RunEventDraft(
            type="stage_started",
            stage=AgentStage.ALGORITHM_DESIGN,
            message="Started designing the solution algorithm",
        )
    )
    await publisher.publish(
        RunEventDraft(
            type="assistant_message",
            stage=AgentStage.ALGORITHM_DESIGN,
            message="Identified a **transportation cost minimization** objective and selected "
            "heuristic construction with local improvement.",
        )
    )
    await publisher.publish(
        RunEventDraft(
            type="warning",
            stage=AgentStage.SOLVING,
            level=EventLevel.WARNING,
            message="This result uses simulated data and exists only to inspect event rendering.",
        )
    )
    await publisher.publish(
        RunEventDraft(
            type="assistant_message",
            stage=AgentStage.SOLVING,
            message="The development solver fake returned a feasible solution with objective 1280",
        )
    )

    artifact = repository.write_artifact_text(
        run_id,
        "demo/report.md",
        "# Simulated Optimization Report\n\nObjective value: 1280\n",
        category="report",
        producer="dbn dev demo-events",
        description="Example report generated by the event-stream demo",
    )
    await publisher.publish(
        RunEventDraft(
            type="artifact_created",
            stage=AgentStage.EXPLANATION,
            message="Generated simulated report",
            payload=artifact.model_dump(mode="json"),
        )
    )
    await publisher.publish(
        RunEventDraft(
            type="stage_started",
            stage=AgentStage.SOLVING,
            message="Started validating simulated result",
        )
    )
    await publisher.publish(
        RunEventDraft(
            type="stage_finished",
            stage=AgentStage.SOLVING,
            message="Capacity and assignment constraints passed",
            payload={"checks_passed": 2, "checks_failed": 0},
            duration_ms=8,
        )
    )
    await publisher.publish(
        RunEventDraft(
            type="run_finished",
            message="Event-stream demo completed",
            payload={"status": "succeeded", "objective": 1280},
        )
    )
    repository.update_record(
        run_id,
        status=RunStatus.SUCCEEDED,
        result_summary={"objective": 1280, "artifact_id": artifact.artifact_id},
    )


@dev_app.command("demo-events")
def demo_events_command(
    ctx: typer.Context,
    debug: bool = typer.Option(
        False,
        "--debug",
        help="Show complete events and structured payloads.",
    ),
    timestamps: bool = typer.Option(
        False,
        "--timestamps",
        help="Show local timestamps before terminal events.",
    ),
) -> None:
    """Generate simulated events and store them in a real Run record."""

    cli = get_cli_context(ctx)
    selected_debug = cli.settings.debug or debug
    repository = RunRepository(cli.settings)
    run_id = generate_run_id()
    run_record = repository.create_run_record(
        run_id=run_id,
        workspace=Path.cwd(),
        command="dbn dev demo-events",
        argv=["dev", "demo-events"],
        config={"debug": selected_debug, "timestamps": timestamps, "demo": True},
    )
    asyncio.run(
        _publish_demo_events(
            repository=repository,
            run_id=run_record.run_id,
            console=cli.console,
            debug=selected_debug,
            timestamps=timestamps,
        )
    )
    cli.console.print(f"[dim]Run record: {repository.run_path(run_record.run_id)}[/dim]")
